-- AlterTable
ALTER TABLE "Post" ALTER COLUMN "createdAt" DROP NOT NULL,
ALTER COLUMN "createdAt" SET DEFAULT TO_CHAR(CURRENT_DATE, 'DD-MM-YYYY');

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "intro" DROP NOT NULL;
